import type { Config } from "./config.js";
import { studioContextForPhone, upsertStudioProfile } from "./studio-store.js";
const MAX_CONTEXT_BYTES=256*1024;const SENSITIVE_CONTEXT_KEY=/(^|_)(password|secret|token|api_key|authorization|credential|cookie|private_key|ssn)($|_)/;
function safeContextValue(value:unknown,depth=0):unknown{if(depth>6||value===null)return value;if(typeof value==="string")return value.slice(0,8000);if(typeof value==="number"||typeof value==="boolean")return value;if(Array.isArray(value))return value.slice(0,100).map(i=>safeContextValue(i,depth+1));if(typeof value!=="object")return undefined;const clean:Record<string,unknown>={};for(const[key,nested]of Object.entries(value).slice(0,200)){const normalized=key.replace(/([a-z0-9])([A-Z])/g,"$1_$2").toLowerCase();if(SENSITIVE_CONTEXT_KEY.test(normalized))continue;const safe=safeContextValue(nested,depth+1);if(safe!==undefined)clean[key]=safe;}return clean;}
async function fetchContextEndpoint(endpoint:string,token:string|undefined,phone:string,fetchImplementation:typeof fetch){const url=new URL(endpoint);if(url.protocol!=="https:")throw new Error("context endpoint must use HTTPS");url.searchParams.set("phone",phone);url.searchParams.set("scope","studio");url.searchParams.set("include","all");const response=await fetchImplementation(url,{headers:token?{authorization:`Bearer ${token}`} :undefined,signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error(`context endpoint returned ${response.status}`);const raw=await response.text();if(Buffer.byteLength(raw,"utf8")>MAX_CONTEXT_BYTES)throw new Error("context endpoint returned more than 256 KB");const parsed=JSON.parse(raw) as unknown;if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("context endpoint must return a JSON object");return safeContextValue(parsed) as Record<string,unknown>;}
function extractStudioPatch(remote:Record<string,unknown>){const studio=(remote.studio&&typeof remote.studio==="object"?remote.studio:{}) as Record<string,unknown>;const member=(remote.member&&typeof remote.member==="object"?remote.member:{}) as Record<string,unknown>;const org=(remote.organization&&typeof remote.organization==="object"?remote.organization:{}) as Record<string,unknown>;const patch:Record<string,unknown>={};for(const[key,sourceKey]of [["name","name"],["vision","vision"],["mission","mission"],["weeklyTheme","weeklyTheme"],["goals","goals"],["knowledge","knowledge"]] as const){const source=key==="name"?member:studio;if(source[sourceKey]!==undefined)patch[key]=source[sourceKey];}if(org.name!==undefined)patch.organization=org.name;return patch;}
export async function fetchMemberContext(config:Config,phone?:string,fetchImplementation:typeof fetch=fetch):Promise<Record<string,unknown>>{if(!phone)return{studioAccess:{status:"identity_missing"}};let local:Record<string,unknown>|null=null;if(config.databaseUrl){try{local=await studioContextForPhone(config,phone);if(Object.keys(local).length>0)return{...safeContextValue(local) as Record<string,unknown>,studioAccess:{status:"connected",source:"mastery_database"}};}catch(error){console.warn("Local Studio context unavailable:",error);}}
const endpoint=config.masteryStudioContextUrl??config.masteryProfileUrl,token=config.masteryStudioContextUrl?config.masteryStudioContextToken??config.masteryProfileToken:config.masteryProfileToken;if(endpoint){try{const remote=await fetchContextEndpoint(endpoint,token,phone,fetchImplementation);if(Object.keys(remote).length>0){if(config.databaseUrl){try{const patch=extractStudioPatch(remote);await upsertStudioProfile(config,phone,patch);const synced=await studioContextForPhone(config,phone);if(Object.keys(synced).length>0)return{...safeContextValue(synced) as Record<string,unknown>,studioAccess:{status:"connected",source:"mastery_database_synced"}};}catch(error){console.warn("Could not persist remote Studio context:",error);}}return{...remote,studioAccess:{status:"connected",source:"mastery_context_api"}};}}catch(error){console.warn("Mastery Studio context unavailable:",error);}}
if(config.databaseUrl){try{await upsertStudioProfile(config,phone,{});const created=await studioContextForPhone(config,phone);return{...safeContextValue(created) as Record<string,unknown>,studioAccess:{status:"connected_no_profile",source:"mastery_database",instruction:"Profile was created automatically. Do not ask the member to troubleshoot or manually relay Studio data."}};}catch(error){console.warn("Could not auto-create Studio profile:",error);}}
return{member:{phone},studioAccess:{status:"not_connected",instruction:"Do not ask the member to paste or screenshot Studio. State that Studio data is not synced yet and continue helping from the conversation."}};}
