import type { Config } from "./config.js";
import { getStudioProfile, getStudioState, studioContextForPhone, updateStudioState, upsertStudioProfile } from "./studio-store.js";
const MAX_CONTEXT_BYTES=256*1024;const SENSITIVE_CONTEXT_KEY=/(^|_)(password|secret|token|api_key|authorization|credential|cookie|private_key|ssn)($|_)/;
function safeContextValue(value:unknown,depth=0):unknown{if(depth>6||value===null)return value;if(typeof value==="string")return value.slice(0,8000);if(typeof value==="number"||typeof value==="boolean")return value;if(Array.isArray(value))return value.slice(0,100).map(i=>safeContextValue(i,depth+1));if(typeof value!=="object")return undefined;const clean:Record<string,unknown>={};for(const[key,nested]of Object.entries(value).slice(0,200)){const normalized=key.replace(/([a-z0-9])([A-Z])/g,"$1_$2").toLowerCase();if(SENSITIVE_CONTEXT_KEY.test(normalized))continue;const safe=safeContextValue(nested,depth+1);if(safe!==undefined)clean[key]=safe;}return clean;}
async function fetchContextEndpoint(endpoint:string,token:string|undefined,phone:string,fetchImplementation:typeof fetch){const url=new URL(endpoint);if(url.protocol!=="https:")throw new Error("context endpoint must use HTTPS");url.searchParams.set("phone",phone);url.searchParams.set("scope","studio");url.searchParams.set("include","all");const response=await fetchImplementation(url,{headers:token?{authorization:`Bearer ${token}`} :undefined,signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error(`context endpoint returned ${response.status}`);const raw=await response.text();if(Buffer.byteLength(raw,"utf8")>MAX_CONTEXT_BYTES)throw new Error("context endpoint returned more than 256 KB");const parsed=JSON.parse(raw) as unknown;if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("context endpoint must return a JSON object");return safeContextValue(parsed) as Record<string,unknown>;}
function objects(remote:Record<string,unknown>){return{studio:(remote.studio&&typeof remote.studio==="object"?remote.studio:{}) as Record<string,unknown>,member:(remote.member&&typeof remote.member==="object"?remote.member:{}) as Record<string,unknown>,org:(remote.organization&&typeof remote.organization==="object"?remote.organization:{}) as Record<string,unknown>};}
function extractProfilePatch(remote:Record<string,unknown>){const{member,studio,org}=objects(remote);const patch:Record<string,unknown>={};if(member.name!==undefined&&member.name!==null)patch.name=member.name;if(org.name!==undefined&&org.name!==null)patch.organization=org.name;if(studio.goals!==undefined&&studio.goals!==null)patch.goals=studio.goals;if(studio.profileKnowledge!==undefined&&studio.profileKnowledge!==null)patch.knowledge=studio.profileKnowledge;return patch;}
function extractSharedPatch(remote:Record<string,unknown>){const{studio,org}=objects(remote);const patch:Record<string,unknown>={};if(org.name!==undefined&&org.name!==null)patch.organization=org.name;for(const key of ["vision","mission","weeklyTheme","knowledge"] as const){if(studio[key]!==undefined&&studio[key]!==null)patch[key]=studio[key];}return patch;}
function sharedMissing(state:any){return !state||!state.vision||!state.mission||!state.weeklyTheme;}
export async function fetchMemberContext(config:Config,phone?:string,fetchImplementation:typeof fetch=fetch):Promise<Record<string,unknown>>{if(!phone)return{studioAccess:{status:"identity_missing"}};
 let existing:any=null,state:any=null;if(config.databaseUrl){try{[existing,state]=await Promise.all([getStudioProfile(config,phone),getStudioState(config)]);}catch(error){console.warn("Local Studio context unavailable:",error);}}
 const endpoint=config.masteryStudioContextUrl??config.masteryProfileUrl,token=config.masteryStudioContextUrl?config.masteryStudioContextToken??config.masteryProfileToken:config.masteryProfileToken;
 if(endpoint&&(!existing||sharedMissing(state))){try{const remote=await fetchContextEndpoint(endpoint,token,phone,fetchImplementation);if(Object.keys(remote).length>0){if(config.databaseUrl){try{const profilePatch=extractProfilePatch(remote),sharedPatch=extractSharedPatch(remote);if(Object.keys(profilePatch).length>0||!existing)await upsertStudioProfile(config,phone,profilePatch);if(Object.keys(sharedPatch).length>0)await updateStudioState(config,sharedPatch);const synced=await studioContextForPhone(config,phone);return{...safeContextValue(synced) as Record<string,unknown>,studioAccess:{status:"connected",source:"mastery_database_synced"}};}catch(error){console.warn("Could not persist remote Studio context:",error);}}return{...remote,studioAccess:{status:"connected",source:"mastery_context_api"}};}}catch(error){console.warn("Mastery Studio context unavailable:",error);}}
 if(config.databaseUrl){try{if(!existing)await upsertStudioProfile(config,phone,{});const local=await studioContextForPhone(config,phone);return{...safeContextValue(local) as Record<string,unknown>,studioAccess:{status:"connected",source:"mastery_database",instruction:"Studio is connected. Use available values directly; never ask the member to manually relay Studio content."}};}catch(error){console.warn("Could not auto-create Studio profile:",error);}}
 return{member:{phone},studioAccess:{status:"not_connected",instruction:"Do not ask the member to paste or screenshot Studio. State that Studio data is not synced yet and continue helping from the conversation."}};
}
